# Core implementation of the dotfiles management logic
#
# Run `make` for a list of targets. See README.md for more details.

# https://stackoverflow.com/a/35698978
CWD := $(abspath $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST))))))

# Gather subdirectories of layers/
LAYERS := $(notdir $(patsubst %/,%,$(wildcard layers/*/)))

STOW_IGNORE := --ignore='^README.*' --ignore='^[.]gitignore$$' --ignore='^LICENSE.*' --ignore='^Makefile$$' --ignore='^install[.]d$$'
STOW_FLAGS := -v -t ~ -d layers $(STOW_IGNORE)

LOCAL_GITCONFIG := $(HOME)/.gitconfig.local

INSTALL_SCRIPTS := $(wildcard layers/*/install.d/*.sh)

.NOTPARALLEL:
.DEFAULT_GOAL := help

.PHONY: help
help: ## Show this help message
	@grep -E "^[a-zA-Z_-]+:.*?## .*$$" $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

.PHONY: install $(INSTALL_SCRIPTS)
install: $(INSTALL_SCRIPTS) ## Run all idempotent installation scripts in layers

$(INSTALL_SCRIPTS):
	@echo "Running installation script: $@"
	@bash $@

.PHONY: submodule
submodule: ## Initialize and update git submodules
	git submodule update --init --recursive

.PHONY: stow
stow: generate-local-git ## Symlink dotfiles for all layers using stow (restow)
	stow -R $(STOW_FLAGS) $(LAYERS)

.PHONY: stow-dry-run
stow-dry-run: ## Dry run of stow command for all layers
	stow --simulate -R $(STOW_FLAGS) $(LAYERS)

.PHONY: unstow
unstow: ## Remove symlinks for all layers using stow
	stow -D $(STOW_FLAGS) $(LAYERS)

.PHONY: generate-local-git
generate-local-git: ## Generate local gitconfig file
	@echo "# Auto-generated by dotfiles Makefile" > $(LOCAL_GITCONFIG)
	@find layers -name "config" -type f | sort | while read -r file; do \
		abs_path=$$(realpath "$$file"); \
		echo "[include]" >> $(LOCAL_GITCONFIG); \
		echo "    path = $$abs_path" >> $(LOCAL_GITCONFIG); \
	done

.PHONY: remove-local-git
remove-local-git: ## Remove local gitconfig file
	rm -f $(LOCAL_GITCONFIG)

.PHONY: clean
clean: remove-local-git unstow ## Full cleanup (unstow and remove local git)

.PHONY: cwd
cwd: ## Print the current directory of the Makefile
	@echo $(CWD)

.PHONY: layers
layers: ## Print the LAYERS variable
	@echo $(LAYERS)
