# Core implementation of the dotfiles management logic
#
# Run `make` for a list of targets. See README.md for more details.

LOCAL_GITCONFIG := $(HOME)/.gitconfig.local

.NOTPARALLEL:
.DEFAULT_GOAL := help

.PHONY: help
help: ## Show this help message
	@grep -E "^[a-zA-Z_-]+:.*?## .*$$" $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

.PHONY: submodule
submodule: ## Initialize and update git submodules
	git submodule update --init --recursive

.PHONY: stow
stow: ## Symlink zsh dotfiles using stow
	stow -v -t ~ -d core zsh

.PHONY: stow-dry-run
stow-dry-run: ## Dry run of stow command for zsh dotfiles
	stow --simulate -vt ~ -d core zsh

.PHONY: generate-local-git
generate-local-git: ## Generate local gitconfig file
	@echo "# Auto-generated by dotfiles Makefile" > $(LOCAL_GITCONFIG)
	@find layers -name "config" -type f | sort | while read -r file; do \
		abs_path=$$(realpath "$$file"); \
		echo "[include]" >> $(LOCAL_GITCONFIG); \
		echo "    path = $$abs_path" >> $(LOCAL_GITCONFIG); \
	done
